server:
  # 端口号
  port: 8801
  servlet:
    context-path: /auth
spring:
  application:
    # 服务名
    name: service_edu
  profiles:
    # 环境设置：dev、test、prod
    active: dev
  datasource:
    # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itrip?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    password: root
    username: root
  jackson:
    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    #    服务器地址   默认本地
    host: 127.0.0.1
    #    端口号   默认6379
    port: 6379
    #    数据库索引  默认为0
    database: 0
    #    链接超时时间  毫秒
    timeout: 1800000
    lettuce:
      pool:
        #        连接池最大连接数   使用负值标识没有限制
        max-active: 20
        #        最大阻塞等待时间 使用负值标识没有限制 默认-1
        max-wait: -1
        #        连接池中的最大空闲链接  默认为8
        max-idle: 5
        #        连接池中的最小空闲链接  默认为0
        min-idle: 0
  mail:
    # 邮箱配置
    host: smtp.qq.com
    # 你的163邮箱
    username: 1415554850@qq.com
    # 注意这里不是邮箱密码，而是SMTP授权密码
    password: ebqopkxmgvmrgahj
    port: 25
    protocol: smtp
    default-encoding: UTF-8

#配置logback日志需要删掉前面的日志配置
mybatis-plus:
  mapper-locations: classpath:com/cskt/itrip/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.cskt.itrip.entry
    #logging:
    #  level:
  #输出日志级别
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
#    root: info

